matrix:
  include:
    - language: rust
      cache:
        - cargo
        - npm
      script: cargo install wasm-pack & wasm-pack build -t nodejs -d "../bin" "./native"

    - language: node_js
      node_js:
        - '10'
        - '12'
      before_script:
        - make setup compile
      cache:
       - cargo
       - npm
