matrix:
  include:
    - language: rust
      before_script:
        - cd native
      script:
        - wasm-pack build -t nodejs -d ../out

    - language: node_js
      node_js:
        - '10'
        - '12'
