matrix:
  include:
    - language: rust
      cache:
        - cargo
        - npm
        - $TRAVIS_BUILD_DIR/bin
#      before_script: HAS_WASM_PACK = $(shell which wasm-pack); if [ -z "$(HAS_WASM_PACK)" ]; then cargo install wasm-pack; fi;
      before_script: make cargo
      script:  wasm-pack build -t nodejs -d "../bin" "./native"

    - language: node_js
      node_js:
        - '10'
        - '12'
      before_script:
        - npm run tsc
      cache:
       - cargo
       - npm
       - $TRAVIS_BUILD_DIR/bin
