matrix:
  include:
    - language: rust
      cache:
        - cargo
        - npm
      before_script: cargo install wasm-pack
      script:  wasm-pack build -t nodejs -d "../bin" "./native"

    - language: node_js
      node_js:
        - '10'
        - '12'
      before_script:
        - nom run tsc
      cache:
       - cargo
       - npm
