matrix:
  include:
    - language: rust
      cache:
        - cargo
        - npm
      before_install: nvm install 12 && nvm use 12
      before_script: make setup && make compile
      script: make check

#    - language: node_js
#      node_js:
#        - '10'
#        - '12'
#      before_script:
#        - npm run tsc
#      cache:
#        - cargo
#        - npm
#        - $TRAVIS_BUILD_DIR/bin
