[package]
name = "chacha-poly1305-rust"
version = "0.1.0"
authors = ["Arik Sosman <git@arik.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin_hashes = "0.7"
wasm-bindgen = "0.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
